### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS for invalid API token

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/dotnet-starter-buttercms#10]
1. ERR_TOO_MANY_REDIRECTS if I set invalid API token to ENV variable.
2. The page should preferably have the same requested URL (`/` instead of redirecting to a 404 page `/Error/404`).

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5487217/164082644-aeac2c2f-6656-4b93-ae16-e30313dec135.png">

**Comment by vlnevyhosteny** [comment]
1. Fixed in https://github.com/ButterCMS/dotnet-starter-buttercms/commit/d3c48c4c08f8763b487c6ac0d534c3927edd7f8c

**Comment by vlnevyhosteny** [comment]
2. I would prefer to have separate pages for Errors. Otherwise I will be needed to handle error in every view which is not IMO good practise. Right now it's done by middleware so anytime and everywhere error is thrown, it will be processed by these error pages.

**Comment by vlnevyhosteny** [comment]
2. Fixed in https://github.com/ButterCMS/dotnet-starter-buttercms/commit/fbfed667d7ac1e5d9745c3502886e91fd9bee0d2
