### ISSUE TITLE
Add env variable PREVIEW to manage articles in preview mode

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/dotnet-starter-buttercms#11]

**Comment by vlnevyhosteny** [comment]
@prokopsimek I can't see **Preview** (or **Testmode**) option for .NET SDK. Am I missing something @ViolanteCodes ?

**Comment by ViolanteCodes** [comment]
@jakelumetta 

Can you weigh in on this - I also do not see preview listed in the SDK (https://github.com/ButterCMS/buttercms-csharp/blob/master/ButterCMS/ButterCMSClient.cs#L52), although we have it specified in a parameter in our API docs (https://buttercms.com/docs/api/?csharp#get-a-single-page) - do you want the preview function just left off of the starter app?

**Comment by jakelumetta** [comment]
Hmm this SDK may never have been enhanced to support that global config.

Can you update it to reflect how the other SDKs (ie JavaScript) support a
preview Boolean config?

Alternatively, you could set a project level CONST for preview value and
then pass that in as a parameter to all API calls.

**Comment by vlnevyhosteny** [comment]
Created https://github.com/ButterCMS/buttercms-csharp/pull/30
