### ISSUE TITLE
certificate error on first load

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/dotnet-starter-buttercms#16]
When starting the app, I initially get a certificate error: [screenshot](https://share.getcloudapp.com/qGuOzqDL) if loading https://localhost:5001/ for the first time. I've also tried using http://localhost:5000, but this automatically redirects to https://localhost:5001. Is there a way to avoid this error screen besides clicking advanced > allow? 

@orlyohreally Do you think forcing https:// is necessary for this app? I think our other starter apps allow http:// connections on localhost?

**Comment by orlyohreally** [comment]
@ViolanteCodes I'm not sure. Usually, localhost does work using http://. We should learn if this is a complex fix and if not, I think we should have it working with both http:// and https:// without this warning message

**Comment by ViolanteCodes** [comment]
@vlnevyhosteny See above - can you advise if we can have it working on both?

**Comment by vlnevyhosteny** [comment]
There is a way how to easily add developer cert for local https https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-6.0&tabs=macos#trust-the-development-certificate .

But enabled http for **development** env in https://github.com/ButterCMS/dotnet-starter-buttercms/pull/28 .

**Comment by ViolanteCodes** [comment]
This works for me - I would expect the developer of this framework to know
how to add the cert if needed, but this at least allows us to bypass the
scary warnings LOL
