### ISSUE TITLE
/landing-page/ route missing; page type/slug is hardcoded to landing-page-with-components

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/dotnet-starter-buttercms#17]
From checklist: 

```
- [ ] Secondary route is set to /landing-page/<slug> to enable previewing in ButterCMS.com
iframe panel, as iframe panel does not currently explicitly allow previewing of index.
- [ ] Page view connects to "landing-page-with-comp
```

trying /landing-page/landing-page-with-components doesn't work in app; neither does /landing-page/alternate-landing-page. I think the `/landing-page/<slug>` route is not set up?

We need the route set up to allow previewing in the butter iframe panel and so that users can preview alternate versions of the landing page for future expansion. Slug should be passed dynamically to /landing-page/ route. Components are set in the /landing-page/ schema; user should be able to move the landing-page components around on any landing page and project/app should match the component partial template to the component in the incoming page object.

Let me know if this doesn't make sense or if you have questions; I can also shoot a video if you think that would be helpful.

**Comment by vlnevyhosteny** [comment]
Hmm, landing-page is setup. `/landing-page/landing-page-with-components` working for me locally and even on heroku https://dotnet-starter-buttercms-tmp.herokuapp.com/landing-page/landing-page-with-components . Could you pls specify what is your response? @ViolanteCodes

**Comment by ViolanteCodes** [comment]
Sorry for the confusion, my error - i was rushing around trying to get things finished before vacation and did not properly check my comment before submitting. I think this comment may have actually been for one of the other projects turned in 🤦 .

That said, landing-page/landing-page-with-components does load for me, landing-page/alternate-landing-page does not.  [screenshot](https://share.getcloudapp.com/qGuOlJ25)?
