### ISSUE TITLE
Setting preview as environment variable?

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/dotnet-starter-buttercms#26]
Is it possible to have preview set with an environment variable, vs storing in appsettings.json? Appsettings.json is a tracked file.

**Comment by vlnevyhosteny** [comment]
Yes, it is possible https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables : 

```
set MyKey="My key from Environment"
set Position__Title=Environment_Editor
set Position__Name=Environment_Rick
dotnet run
```

**Comment by ViolanteCodes** [comment]
Great, can we have this implemented and have readme updated to reflect this change, so that preview is set with environment variable (true by default) vs storing in appsettings.json? Management of preview through a tracked file is cumbersome, harder to test, and means that users cannot do multiple deployments from the same repo without figuring out an appsettings.json workaround

**Comment by vlnevyhosteny** [comment]
If you set `ButterCMSPreview=false` than it would be false also in runtime no matter what is in `appsettings.json`. Thats because priorities are like:

1. Environment variable 
2. appsettings.<some-environment>.json
3. appsettings.json

This is described in README:

> By default, your starter project is set up to allow previewing of draft changes saved in your ButterCMS.com account. To disable this functionality, set ButterCMSPreview to false in appsettings.json.

**Comment by ViolanteCodes** [comment]
@vlnevyhosteny 

Sorry, I think maybe there's some error in the comment above? It looks like priority 2 and priority 3 are the same?

If the env value supercedes the the appsettings.json value, then shouldn't the readme line be something like: 

`By default, your starter project is set up to allow previewing of draft changes saved in your ButterCMS.com account. To disable this functionality, set ButterCMSPreview value to false in your .env file or in appsettings.json. Note that values set in the .env file will override values in appsettings.json.`

?

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes 

Sorry for the comment error. Probably didn't save after edit.

> If the env value supercedes the the appsettings.json value, then shouldn't the readme line be something like:

> By default, your starter project is set up to allow previewing of draft changes saved in your ButterCMS.com account. To disable this functionality, set ButterCMSPreview value to false in your environment variables or appsettings.json. Note that a value set in your environment variables takes precedence over appsettings.json.

You are right thats much better and I will update README. Updated in -> https://github.com/ButterCMS/dotnet-starter-buttercms/pull/35

I changed instructions to setting variable because it is not **dotnet user-secret** but just system environment variable. 

> To set in environment variables on **Mac/Linux**:
>
> $ export ButterCMSPreview=false
>
> To set in environment variables on **Windows**:
>
> $ set ButterCMSPreview=false

Regarding this ^^^ disabling preview mode can be done just with Heroku config (see image).

<img width="1366" alt="Screenshot 2022-07-06 at 7 50 33" src="https://user-images.githubusercontent.com/15954946/177478208-d5cb20c0-58e2-4faa-b2c4-554b05d39e01.png">

**Comment by ViolanteCodes** [comment]
Hi @vlnevyhosteny:

Using `set ButterCMSPreview=false` didn't work for me. Here is a video - please ignore the comment re: heroku at the end, turns out I had a typo with heroku and was able to get that part no sweat. [Video of setting env in terminal](https://share.getcloudapp.com/o0uGGbeQ)
