### ISSUE TITLE
Dotenv to store environment variables

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/dotnet-starter-buttercms#5]
Is that possible to configure dotenv lib to store local environment variables?

**Comment by vlnevyhosteny** [comment]
It is possible https://dusted.codes/dotenv-in-dotnet but not recommended and standard way in .NET.

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes, is `.env` config mandatory? .NET has its own solution which is described in README. In case its mandatory I am able to use .env parser.

**Comment by ViolanteCodes** [comment]
@vlnevyhosteny I think we should do whatever is best practice for handling environmental variables in that framework, and whatever will feel the most clean, logical, and secure to developers used to that framework. If .NET's recommended method of handling environmental variables is not a .env, then let's use the recommended method instead.

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes Ok. It is possible to deploy eventually on Heroku without .env file. https://github.com/ButterCMS/dotnet-starter-buttercms/issues/6
