### ISSUE TITLE
One-click deploy button and demo on Vercel, one-click for Heroku

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/dotnet-starter-buttercms#6]
Why did you choose Azure?

[vlnevyhosteny](https://github.com/vlnevyhosteny) commented [3 days ago](https://github.com/vlnevyhosteny/ButterCMS.Starter/issues/1#issuecomment-1088298403)
Deploying ASP.NET Core app is not possible on Vercel. For Heroku it is possible only in case of Docker. So I've chosen Azure because there are tools made for ASP.NET Core.

**Comment by prokopsimek** [comment]
It would be possible with a docker image: https://dev.to/alrobilliard/deploying-net-core-to-heroku-1lfe

Ask Maria.

**Comment by vlnevyhosteny** [comment]
Hi @ViolanteCodes , is it OK from your side that I would Dockerize .NET app and create one-click deploy on Heroku?

**Comment by vlnevyhosteny** [comment]
Closes #7

**Comment by ViolanteCodes** [comment]
I am thinking we do not want docker - I think azure would be fine, but let me check with @jakelumetta on this one. Jake - heroku not possible for .net without docker, is azure okay?

**Comment by vlnevyhosteny** [comment]
@jakelumetta Yeah, it should be possible. Right now there is some problem with it but I will debug it. 

Yeah, Azure is also Microsoft product, so .NET-Azure is like Next.JS-Vercel.

**Comment by vlnevyhosteny** [comment]
I was eventually able to deploy on Heroku using third-party buildpack for Heroku (https://github.com/jincod/dotnetcore-buildpack). The workflow is the same like for https://github.com/ButterCMS/django-starter-buttercms .

There is a deployment under my account https://dotnet-starter-buttercms-tmp.herokuapp.com .
